newcasting apply command to remote server if set

diff --git a/bin/newcasting b/bin/newcasting
--- a/bin/newcasting
+++ b/bin/newcasting
@@ -136,11 +136,17 @@ do
 done
 
 exec 1>&3
+
+if echo "$remote" | grep -q ":"; then
+	remote_server=$(echo $remote | cut -d ":" -f 1)
+	if [ "$remote_server" != "" ]; then
+		echo "Applying on remote server $remote" >&2
+		remote_command=$(dirname $0)/$(basename $0)
+		echo "ssh -t $remote_server $remote_command $client $job $casting" >&2
+		ssh -t $remote_server $remote_command $client $job $casting | sed "s/^/  $remote_server /">&2
+	else
+		echo "could not resolve remote server from $remote" >&2
+	fi
+fi
+
 cat $TMP.lastcreated
-
-# cd "$castingdir" || exit 5
-#ln -s "$base/$client/web/$job/$casting" web || exit 6
-#cd "$castingdir/dv" || exit 7
-#ln -s "$base/$client/web/$job/$casting/.browsercache" || exit 8
-
-# echo "$castingdir"
