(fix) rethumb-comedian: include thumb size in sync, better video matching
- fix small thumbs not included when syncing from remote
- fix name detection including group videos

diff --git a/bin/rethumb-comedian b/bin/rethumb-comedian
--- a/bin/rethumb-comedian
+++ b/bin/rethumb-comedian
@@ -1,54 +1,62 @@
 #!/bin/bash
 
-director=$(pwd | sed 's:.*/castings/::' | cut -d / -f 1)
+director=$(pwd\
+	| sed 's:.*/castings/::' \
+	| cut -d / -f 1
+)
 
 export PATH=$(dirname "$0"):$PATH
 . $(which casting-helpers) || exit 1
 
 if echo "remote $remote" | grep -q ":"
 then
-  remotehost=$(echo "$remote" | cut -d : -f 1)
-  ssh $remotehost "cd $PWD/.sources && $0 $@" \
-  && rsync -Waz $remote/$director/$job/$casting/.browsercache/ thumbnails/ --exclude "*thumb.jpg"
-  exit $?
+	remotehost=$(echo "$remote" | cut -d : -f 1)
+	ssh $remotehost "cd $PWD/.sources && $0 $@" \
+	&& rsync -Waz $remote/$director/$job/$casting/.browsercache/ thumbnails/
+	exit $?
 fi
 
 [ "$1" ] || end $? "usage $PGM -n|+n c1 [c2]"S
 echo "$1" | egrep -q "^[\+-][0-9\.]+$" && offset=$1 && shift
 if [ ! "$offset" ]
 then
-  [ "$director" = "bobines" -o "$director" = "ludivine" ] && offset=-1 || offset=+1
+	[ "$director" = "bobines" -o "$director" = "ludivine" ] && offset=-1 || offset=+1
 fi
 
 [ -f "liste" ] || end $? "List not found, not a casting directory?"
 
+cat liste | tr "\t" " " | sed "s://.*::; s:(.*::; s/[[:blank:]]+/ /g" > $TMP.clean-list
+
 for c in $@
 do
-  name=$(sed "s://.*::" liste | grep "[[:blank:]]$c-[^,]*$" | sed -E "s/^[0-9,-]+[[:blank:]]+//" | head -1)
-  [ ! "$name" ] && log 1 "Comedian $c not found" && continue
-  echo "$name"
-  v=$(sed "s://.*::" liste | grep "[[:blank:]]$c-" | cut -d " " -f 1 | cut -f 1 | cut -d "-" -f 1 | cut -d "," -f 1 | head -1)
-  [ ! "$v" ] && log 1 "No video found for comedian $c $name" && continue
-  [ ! -f "$v.mov" ] && log 1 "Video $v.mov not found" && continue
-  # echo $v.mov
-  # d=$(grep ^$v.mov times | sed -E "s/.*[[:blank:]]([0-9]+)[[:blank:]]/\1/")
-  d=$(grep ^$v.mov times | sed "s/.*:[0-9]* *//")
-  [ ! "$d" ] && log 1 "Duration not found for video $v.mov" && continue
-  if [ -f .$v.thumbtime ]
-  then
-    t=$(cat .$v.thumbtime)
-  else
-    echo "$offset" | egrep "\+" && t=0 || t=$d
-  fi
-  # t=$(grep ^$v.mov times | sed -E "s/.*[[:blank:]]([0-9]+)[[:blank:]]/\1/")
-  [ "$t" ] || t=0
-  t=$(echo $t $offset | bc)
-  (( $(echo "$t < 0 || $t > $d" | bc -l) )) && log 1 "time $t not between 0 an $d" && continue
-  echo "$t" | grep -q "^\." && t=0$t
-  echo "$t" > .$v.thumbtime
-  qt-thumbnailswide.sh -f -l -$t $v.mov && rm -f ../.browsercache/$c-* \
-  && batchthumbs liste >/dev/null \
-  && echo "$t" > .$v.thumbtime
+	name=$(
+		egrep -i "\s$c-[a-z][^,]*$" $TMP.clean-list \
+		| sed -E "s/^[0-9,-]+[[:blank:]]+//" | head -1
+	)
+	[ ! "$name" ] && log 1 "Comedian $c not found" && continue
+	echo "$name"
+	v=$(sed "s://.*::" liste | grep "[[:blank:]]$c-" | cut -d " " -f 1 | cut -f 1 | cut -d "-" -f 1 | cut -d "," -f 1 | head -1)
+	[ ! "$v" ] && log 1 "No video found for comedian $c $name" && continue
+	[ ! -f "$v.mov" ] && log 1 "Video $v.mov not found" && continue
+	# echo $v.mov
+	# d=$(grep ^$v.mov times | sed -E "s/.*[[:blank:]]([0-9]+)[[:blank:]]/\1/")
+	d=$(grep ^$v.mov times | sed "s/.*:[0-9]* *//")
+	[ ! "$d" ] && log 1 "Duration not found for video $v.mov" && continue
+	if [ -f .$v.thumbtime ]
+	then
+		t=$(cat .$v.thumbtime)
+	else
+		echo "$offset" | egrep "\+" && t=0 || t=$d
+	fi
+	# t=$(grep ^$v.mov times | sed -E "s/.*[[:blank:]]([0-9]+)[[:blank:]]/\1/")
+	[ "$t" ] || t=0
+	t=$(echo $t $offset | bc)
+	(( $(echo "$t < 0 || $t > $d" | bc -l) )) && log 1 "time $t not between 0 an $d" && continue
+	echo "$t" | grep -q "^\." && t=0$t
+	echo "$t" > .$v.thumbtime
+	qt-thumbnailswide.sh -f -l -$t $v.mov && rm -f ../.browsercache/$c-* \
+	&& batchthumbs liste >/dev/null \
+	&& echo "$t" > .$v.thumbtime
 done
 
 # [ "$1" ] && standard="$1"
